AWSTemplateFormatVersion: "2010-09-09"
Description: Markdown Memo Portal - WAF in us-east-1

Resources:
  # CloudWatch Logs(WAF Logging)
  MkmemoportalWafLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: aws-waf-logs-mkmemoportal
      RetentionInDays: 90

  # WAF
  MkmemoportalWaf:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: mkmemoportal-waf
      Scope: CLOUDFRONT
      Description: Web ACL for CloudFront distribution
      DefaultAction:
        Allow: {}
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: MkmemoportalWafMetric

  MkmemoportalWafLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt MkmemoportalWaf.Arn
      LogDestinationConfigs:
        - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:aws-waf-logs-mkmemoportal

Outputs:
  WafWebAclArn:
    Description: WAF Web ACL ARN in us-east-1
    Value: !GetAtt MkmemoportalWaf.Arn
    Export:
      Name: !Sub ${AWS::StackName}-WafWebAclArn
