AWSTemplateFormatVersion: "2010-09-09"
Description: Markdown Memo Portal in us-east-1

Parameters:
  S3LambdaEdgeBucketName:
    Type: String
    Description: S3 bucket that stores Lambda@Edge deployment artifacts

Resources:
  # CloudWatch Logs(WAF Logging)
  MkmemoportalWafLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: aws-waf-logs-mkmemoportal
      RetentionInDays: 90

  # WAF
  MkmemoportalWaf:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: mkmemoportal-waf
      Scope: CLOUDFRONT
      Description: Web ACL for CloudFront distribution
      DefaultAction:
        Allow: {}
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: MkmemoportalWafMetric

  MkmemoportalWafLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt MkmemoportalWaf.Arn
      LogDestinationConfigs:
        - !GetAtt MkmemoportalWafLogGroup.Arn

  # IAM Role
  MkmemoportalIAMRoleLambdaEdge:
    Type: AWS::IAM::Role
    Properties:
      RoleName: mkmemoportal-iam-role-lambda-edge
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: mkmemoportal-ssm-parameter-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - !Sub arn:aws:ssm:ap-northeast-1:${AWS::AccountId}:parameter/mkmemoportal/*

  # Lambda Functions(Lambda@Edge)
  MkmemoportalLambdaEdgeViewerRequest:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: mkmemoportal-lambda-edge-viewer-request
      Runtime: nodejs22.x
      Handler: edge_viewer_request/index.handler
      Role: !GetAtt MkmemoportalIAMRoleLambdaEdge.Arn
      Code:
        S3Bucket: !Ref S3LambdaEdgeBucketName
        S3Key: edge_viewer_request.zip
      Timeout: 5
      MemorySize: 128

  MkmemoportalLambdaEdgeViewerRequestVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref MkmemoportalLambdaEdgeViewerRequest
      Description: Lambda@Edge Viewer Request Version

Outputs:
  WafWebAclArn:
    Description: WAF Web ACL ARN in us-east-1
    Value: !GetAtt MkmemoportalWaf.Arn
    Export:
      Name: !Sub ${AWS::StackName}-WafWebAclArn
  LambdaEdgeViewerRequestVersionArn:
    Description: Lambda@Edge Viewer Request Version ARN
    Value: !Ref MkmemoportalLambdaEdgeViewerRequestVersion
    Export:
      Name: !Sub ${AWS::StackName}-LambdaEdgeViewerRequestVersionArn
