name: Build and Deploy Backend

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  AWS_STACK_NAME: mkmemoportal-stack-backend
  PYTHON_VERSION: "3.12"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unittests with Coverage
        run: |
          pytest --cov=lambdas \
            --cov-report=term-missing \
            --cov-report=xml:lambdas/coverage.xml \
            --cov-fail-under=80 \
            lambdas/tests

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Lambda Functions and Layer codes
        run: |
          cd lambdas/create_memo && zip -r ../../create_memo.zip app.py __init__.py && cd ../../
          cd lambdas/delete_memo && zip -r ../../delete_memo.zip app.py __init__.py && cd ../../
          cd lambdas/get_memo && zip -r ../../get_memo.zip app.py __init__.py && cd ../../
          cd lambdas/list_memos && zip -r ../../list_memos.zip app.py __init__.py && cd ../../
          cd lambdas/update_memo && zip -r ../../update_memo.zip app.py __init__.py && cd ../../
          cd lambdas/layer && zip -r ../../layer.zip python && cd ../../

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda Functions and Layer codes
        run: |
          aws s3 cp create_memo.zip s3://${{ vars.S3_BACKEND_BUCKET_NAME }}/create_memo.zip
          aws s3 cp delete_memo.zip s3://${{ vars.S3_BACKEND_BUCKET_NAME }}/delete_memo.zip
          aws s3 cp get_memo.zip s3://${{ vars.S3_BACKEND_BUCKET_NAME }}/get_memo.zip
          aws s3 cp list_memos.zip s3://${{ vars.S3_BACKEND_BUCKET_NAME }}/list_memos.zip
          aws s3 cp update_memo.zip s3://${{ vars.S3_BACKEND_BUCKET_NAME }}/update_memo.zip
          aws s3 cp layer.zip s3://${{ vars.S3_BACKEND_BUCKET_NAME }}/layer.zip

      - name: Deploy Backend AWS Resources
        run: |
          aws cloudformation deploy \
            --template-file resources/backend.yaml \
            --stack-name ${AWS_STACK_NAME} \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              S3BackendBucketName=${{ vars.S3_BACKEND_BUCKET_NAME }}
