name: Run Lint in SPA before Merging Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/lint-spa.yaml
      - spa/**

env:
  NODE_VERSION: "22.17.1"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: spa/package-lock.json

      - name: Run Lint
        uses: reviewdog/action-eslint@v1
        with:
          fail_level: error
          filter_mode: file
          level: warning
          reporter: github-pr-review
          workdir: spa
