name: Run Tests and Lint in Backend before Merging Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - lambdas/**
      - .pylintrc
      - pytest.ini
      - requirements.txt

env:
  PYTHON_VERSION: "3.12"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        run: pylint lambdas/**/*.py

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests with coverage
        run: |
          pytest --cov=lambdas \
            --cov-report=term-missing \
            --cov-report=xml:lambdas/coverage.xml \
            --cov-fail-under=80 \
            lambdas/tests
